shared:
    image: node:20
    steps:
        - echo: echo test
    annotations:
        screwdriver.cd/virtualJob: true
jobs:
    main:
        requires:
            - ~pr
            - ~commit
    publish:
        requires:
            - main
